name: discogs_single
on:
  workflow_dispatch:
    inputs:
      store:
        description: 'Select a record store'
        required: true
        type: choice
        options:
          - juno
          - redeye
          - phonica
          - yoyaku
jobs:
  scrape-discogs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
        python3 -m pip install --upgrade python3-discogs-client
        python3 -m pip install --upgrade yt-dlp
        python3 -m pip install --upgrade rapidfuzz
    - name: populate_discogs
      run: |
        cd scrape
        python3 discogs.py -store ${{ github.event.inputs.store }} -key '${{secrets.SERVICE_ACCOUNT}}' -discogs-key '${{secrets.DISCOGS_KEY}}' -releases 1024 -searches 100
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "- update ${{ github.event.inputs.store }} releases" || true
        git pull --rebase
        git push origin HEAD:main