name: discogs
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  scrape-discogs:
    strategy:
      matrix:
        store: [redeye, juno, phonica, yoyaku]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
        python3 -m pip install --upgrade python3-discogs-client
        python3 -m pip install --upgrade yt-dlp
        python3 -m pip install --upgrade rapidfuzz
    - name: populate_discogs
      run: |
        cd scrape
        python3 discogs.py -store '${{matrix.store}}' -key '${{secrets.SERVICE_ACCOUNT}}' -discogs-key '${{secrets.DISCOGS_KEY}}' -releases 1024 -searches 100
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "- update '${{matrix.store}}' releases" || true
        git pull --rebase
        git push origin HEAD:main