name: scrape_single
on:
  workflow_dispatch:
    inputs:
      store:
        description: 'Select a record store'
        required: true
        type: choice
        options:
          - juno
          - redeye
          - phonica
          - yoyaku
jobs:
  update-stores:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
    - name: scrape_and_commit
      run: |
        cd scrape
        python3 dig.py -update-stores -key '${{secrets.SERVICE_ACCOUNT}}'
  scrape-single:
    needs: update-stores
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
        python3 -m pip install --upgrade selenium
    - name: scrape_and_commit
      run: |
        cd scrape
        python3 dig.py -store ${{ github.event.inputs.store }} -key '${{secrets.SERVICE_ACCOUNT}}' -clear-trackers -verbose -urls
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "- update ${{ github.event.inputs.store }} releases" || true
        git pull --rebase
        git push origin HEAD:main